name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:

    runs-on: ubuntu-22.04
    
    container:
      image: elementary/docker:next-unstable
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apt update
        apt install -y meson libgranite-dev libswitchboard-2.0-dev libxml2-dev libgnomekbd-dev libhandy-1-dev libibus-1.0-dev libxklavier-dev valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build install

  lint:

    runs-on: ubuntu-latest
    
    container:
      image: valalang/lint
      
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: io.elementary.vala-lint -d .
